### ISSUE TITLE
Is it possiable to control source service or the destination service version in rate limit

### ISSUE THREAD

**Issue by garyyang85** [envoyproxy/envoy-filter-example#150]
I am using rate limit since istio 1.1, now seems the rate limit usage mode is completely changed. Just have a quick test about demo envoy filter configuration, https://istio.io/v1.9/docs/tasks/policy-enforcement/rate-limit/, it works good. Here is more detail scenario.  I have below configuration to control source(production service) to destination(details v1) worked before. But now by envoy filter, seems it not easy to control the **source** service or the **destination service version**? Thanks for your kindly help.
```
spec:
  quotas:
    - name: requestcount.quota.istio-system
      maxAmount: 5000
      validDuration: 1s
      overrides:
        - dimensions:
            destination: details
            destinationVersion: v1
            source: productpage
          maxAmount: 1
          validDuration: 1s
```
